### ISSUE TITLE
My Cars: Additional default characteristics

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#135]
Propose adding default values for
- [x]  Payload
- [x] Cabin Temp
- [x] Power Factor
- [x] Model X 5 Seater #302

**Comment by aesculus** [comment]
It remembers from last trip edit for right now. So if you change payload or cabin temp, next time it is used it grabs your last value.

Need to find some room for this on the My Cars panel.

**Comment by EVGrokker** [comment]
On the iPhone, the My Cars panel already requires scrolling. Is there a layout issue on the iPad?

**Comment by aesculus** [comment]
Right now everything fits on the iPad without scrolling.  If I add this it will need it for sure.

Lets see what else washes ashore in the next few weeks and then we can decide if it warrants the hit.

**Comment by aesculus** [comment]
From a user on power factor being an My Cars option:
>Speaking from my own personal needs, having it in the car would be useful because I could create a Model X and a Model X - Towing to differentiate. But the slider is easy enough.

**Comment by EVGrokker** [comment]
It could be in both places. The value in My Car would be the default, the value in the Edit Segment Details would override, as has been proposed for other Cockpit settings.

**Comment by aesculus** [comment]
Yes. I was not thinking of removing it from Edit Segment Details, but just adding it to the My Cars too.

And while I am on the subject: Today the pf gets set and becomes the default after the last edit in details. This feature would eliminate that function and replace the new segment pf from the My Cars.

So the only reason you would go to Edit Segment Details to change the pf would be because of that one segments needs. It would have no other effect.

**Comment by aesculus** [comment]
The default characteristics of payload, speed adjust, power factor and cabin temp are now in My Cars for each car. V1.2 (23).

These factors will be used when new trips are created. For trip segments I propose we stay with cloning the prior segments values.

**Comment by aesculus** [comment]
See the comments about these being trip vs segment based in issue #303
