### ISSUE TITLE
Optimized route display on map different from Segment Summary details

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#146]
v 1.1.3 (4)

1. New Trip: Sand Dollar Inn, Moclips WA to Bend, OR, single segment
2. Auto charger selection
3. Calculate

Displayed route on map shows two supercharger stops selected during optimization, Centralia WA and Sandy OR, both with 'A' markers, indicating auto-assigned.

Segment Summary says that the Centralia Supercharger stop is not required, and the 'A' marker is not shown in this list. Touching the waypoint shows that the arrival SoC is 58%, departure is 60%.

Deleting the waypoint (since EVTO is telling me I don't need to stop) now shows arrival SoC at Sandy supercharger at 7%, well below my default minimum SoC.

Optimizing segment adds the Centralia supercharger back onto the route, but once again Segment Summary shows no stop required.

Optimizing segment again shows that Centralia is now charging from 58% to 72%, which seems correct, as the downstream charging stop at Sandy OR is now 22% > 73%.

**Comment by aesculus** [comment]
Can you use the feedback and share with me? You will have to put in the email as I am still working on that.

**Comment by EVGrokker** [comment]
Email sent via Feedback

**Comment by aesculus** [comment]
I did not get this trip but the Seattle Moclips one. Can you resend?

**Comment by aesculus** [comment]
Nevermind. Wrong email. :-)

**Comment by aesculus** [comment]
OK. I will use this trip as a sample. For my reference it's ID [bvx2u14qa7stivu7q0igc]

What is going on here is a bit of a nuance. The server does not currently take into account weather.  So somethings on the fringe you get chargers that are not needed (or so it appears). But what is happening is that you get a much finer weather forecast with the added stop. So if the weather is much different the optimization gets additional info to work on. 

It may be hard to notice but the first charger is gray. Maybe I should lighten that gray up a bit and/or fill in the center with gray too. Its hard to tell the difference between that and a green one.

I will dive into this trip to make sure there is not something else going on here too. Nice catch.

**Comment by aesculus** [comment]
I looked at this again. The issue was that if you need less than a few minutes of charge I just decided not to stop. But then the optimization model thought you should and the SOC % got out of wack too.

So I just changed the algorithm to charge for at least 10 mins (+ 5 setup time) even if you really only needed a few minutes. The user can then decide to skip the charger if it looks like they will have sufficient charge to make it to the next stop or pull in for the 15 minutes min.  The weather can be so variable it will probably be the bigger difference anyway.

Fixed in V1.1.4
