### ISSUE TITLE
Waypoint Inspector: Exiting Google Street View or Edit Waypoint dialog should return to Waypoint Inspector

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#166]
In the Waypoint Inspector, touching the eyeball icon brings up Google Street View. If user touches the arrow at the top left of the image, next to the waypoint's street address, the Waypoint Inspector should be displayed again. The same should be true after invoking and dismissing the Edit Waypoint dialog with the pencil icon.

In other words, treat the Street View display and Edit Waypoint dialogs as modal.

As previously discussed, invoking Help overlays the Waypoint Inspector.

**Comment by aesculus** [comment]
I went out of my way to close the thing because I thought you did not want dialogs over the top of each other! :-(

Anyway it does not get hidden now. But don't be upset by the fact that selecting the eye moves the Waypoint inspector.  A Google thing that is not easy to fix at the present.

Fixed in V1.1.3 (7)
