### ISSUE TITLE
Purchase Subscription dialog text revisions

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#212]
**Propose the following edits:**

~~Unlimited planning for one year. You can cancel within the first 30 days for no charge.~~ A Yearly Subscription Fee allows you to store and manage multiple trips created with EVTO. You may cancel your subscription with the first 30 days for no charge.

~~Terms of Use http://www.digitalaudioguides.com/dag-terms-of-use/~~

~~The~~ Our Terms of Use and Privacy Policy are ~~also~~ available on the main menu…

**The bullet list font is smaller than the rest of the dialog, it should be the same size.**

**What does the last bullet item refer to? Is there a free trial period on Android that's not available on iOS? If you, you need to delete that bullet in an iOS version of this dialog.**

~~Is this what you want to do?~~ Purchase a Multi-Trip Yearly Subscription?

---

![purchase subscription](https://cloud.githubusercontent.com/assets/26678403/25003433/9f33400a-200c-11e7-8371-d6891c2d5dbd.PNG)

**Comment by aesculus** [comment]
I think I can get rid of all that legal stuff (small print). There was confusion for a few weeks between me and Apple on where to display it.  The last update was approved in less than 48 hours.

Whenever I am brave enough I will pull the small print and see if it passes. If not we just loose a day in the process.

I think with V1.1.4 its worth a try to see if these changes get accepted since there are no major features that must get out quickly.

**Comment by aesculus** [comment]
Fixed in V 1.1.4 (2) but Apple has to approve the first part:

>A Yearly Subscription Fee allows you to store and manage multiple trips created with EVTO. You may cancel your subscription within the first 30 days for no charge. This subscription will auto-renew before the subscription expires unless cancelled.

**Comment by aesculus** [comment]
I think this was an updated version of this one: https://github.com/aesculus/EVTO-App-Feedback/issues/58
