### ISSUE TITLE
New Help panel appearance (1.1.4)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#218]
The new help panel appearance and behavior is very nice. Adding the contrasting header bar helps visually differentiate the panel. I believe that with the addition of the header bar, you've also changed the behavior of that panel, as earlier versions scrolled the title area off-screen when scrolling down into the rest of the content.

You had previously suggested that 'Help' should somehow be in that title header, and with the current behavior and appearance, I agree.

I'd propose prefixing each section with the question mark icon in the header. 

For example:
- [?] Edit Segment Details
- [?] Waypoint Inspector
- [?] Plan Trip

This will give the help panel visual consistency with the other dialog headers which are prefixed by their respective icons.

**Comment by aesculus** [comment]
It turns out the icon makes many of the tiles spill into the close icon, which I could fix by having them go to a second line, but I did not like that.

I think we are good without it. As you stated before it's pretty evident what's happening since they selected the Help icon on the dialog and that thing suddenly popped up.

So you converted me and there is no going back. :-)
