### ISSUE TITLE
Edit Segment Details dialog: Power Factor confusion

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#220]
I'm not sure how to think about the Power Factor slider in the Edit Segment details. 

I know it's used to tell EVTO I'm using more power than typical, for example when towing, but it's not clear how the number relates to the increased load.

I think it should either be expressed as a percentage, where 100% would mean 'no penalty', or as a number, where 1.0 represents 'no penalty'.  If you can explain it to me again, I can also try to improve the help text describing it.

**Comment by aesculus** [comment]
It's not easy to explain. :-)

It goes into effect anywhere driving energy comes into play. It can act like you are driving faster, but I don't change the estimated times because of this. It also has effects in gravity situations too. And can also change the rolling resistance of the car.

Basically each digit is a 10% effect on those factors.  And you can have a negative effect too if you find yourself driving more conservatively (ie not as fast or maybe you are hypermiling etc).

Note this is way more than a Speed Factor that just increases the speed of the car.

**Comment by EVGrokker** [comment]
A couple of ideas here.

Since it's apparently not a linear effect, and there's no easy way to explain to users how to estimate a number they should use here, how about switching to words to describe a range of driving styles, or placing words along the slider as a guide?

Even though it's far more likely that a user would be setting a positive value, the default position should be centered. Even if you clip the possible range of returned values, visually it should look like neutral is in the middle.

I realize that Conservative - Aggressive doesn't accurately describe the effect. For example, towing a trailer doesn't qualify as 'aggressive', yet that's the direction it needs to go. So maybe the words would be 'Less' to 'More'. Or 'Negative' to 'Positive'. 
 
If you need to have the number in another format other than -5 to +5, you can just scale what you show the user to what you need internally.

---


![power factor](https://cloud.githubusercontent.com/assets/26678403/25071374/60682314-2272-11e7-86db-215c293c4c08.png)

**Comment by aesculus** [comment]
I already had one user complain that they could not adjust the pf because it was too small. There should be little reason to ever go below 0 unless the user is really hypermiling.  But towing a large trailer can really suck more energy, maybe at 4,5, or 6.  So it's impossible to balance this around 1 for example, the nominal setting.

Now the control and dialog could use something to help the user decide what value to set.  I have had some users that were chasing this factor on different segments of a trip so that needs to be pinned down as to why. Was it that they did not set the trip date/time before leaving? Was the forecast wrong? 

I would really like to get some users who use the logging tools to start comparing actual vs estimated.

**Comment by aesculus** [comment]
I added the need to change the drive time which is directly related to this issue. (issue #303 )

**Comment by EVGrokker** [comment]
Superseded by #306
