### ISSUE TITLE
Segment Summary incorrect after manually adding waypoint

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#230]
Trip: Sand Dollar Inn & Cottages, [ngnrbmhbm3mv6xgx2inzde]

1. New Trip, single-segment, Auto. Seattle - Sand Dollar Inn & Cottages, Moclips WA. EVTO calculates trip with no charger required.
2. Zoom into Olympia WA area, find Children's Museum north of downtown, press and hold on Jefferson street just north of POI icon.
3. Add waypoint with 60 minutes stop time.
4. Rename waypoint to "Children's Museum"
5. Optimize Segment. 
6. EVTO adds Aberdeen WA as automatic waypoint.
7. Touch Aberdeen pin, note that arrival/departure SoC levels are 25/43.
8. Open Segment Summary. Note that Aberdeen Supercharger stop says "No stop required", disagreeing with waypoint inspector details.

---

![segment summary error](https://cloud.githubusercontent.com/assets/26678403/25044598/b57bf32e-20e4-11e7-85c0-26e51c9ae820.PNG)

**Comment by aesculus** [comment]
Before I get into this: This trips destination has "Plan last charging stop for a return trip" selected in the destination. It also has a arrival SOC of 20%.  Is that what you wanted to do?

Having said that the real bug here is that it is trying to reserve enough energy to get you back to the Children's museum (or so it says), when you really don't have a charger defined at all. It should probably try to get you back home or to the closest charger along your route.

Note the Aberdeen charger is grey. Probably because it wanted to stop there so it could get enough energy to get back to that point from Moclips without charging there. But the app is somehow skipping that because it did not use it.

**Comment by aesculus** [comment]
This problem is no longer valid since we removed the ability to reserve energy to go back. This would have to be done as an out and back trip now.
