### ISSUE TITLE
Decide if help subjects should be separated with a line

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#300]
Right now some of the help has the line separating topics and some don't. We need to decide if we like that feature or not and make all the help uniform.

Ie see main help for lines and Current Trips help for none.

Personally I like the cleaner look without the lines.

**Comment by EVGrokker** [comment]
This was intentional.

The Plan menu Help text and the Main menu Help text each have unrelated topics, which is why I included the horizontal rules separating topics.

The Current Trip menu Help topics are all about the same general theme, which is why I felt that lines were not as necessary.

If you want consistency, I'd vote for always using the hr elements between items, rather than removing them. I'd be fine with that.

**Comment by aesculus** [comment]
I'll go with what you have then, since I am not excited by the lines.

Just make sure that I did not screw up and put lines where they don't belong or left some out where you wanted them
