### ISSUE TITLE
Segment Summary times incorrect after updating Segment departure time

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#329]
V 1.2 (6).

Trip ID [317lgae66vs8yob00urpdi] and the PIN [1234]

Activate second segment. 
Touch Depature pin (Sand Dollar Motel), note that Departure time is 10AM.
Touch waypoint pin at Shelton (Smoking Mo's), note that Arrival time is 11:40am.
Open Plan | Segment Summary dialog.
Note that Elapsed time for Smoking Mo's is 5:13.

The original departure time from the motel was earlier in the morning. It appears Segment Summary details are not updated from the latest segment data.

Also, the Segment metrics at the bottom are wrong. The actual trip time, departing at 10am, arriving in Seattle at 4:06pm, should be 6:06. The Segment Summary metrics show 8:33.

**Comment by aesculus** [comment]
It was penalizing you for charging before you started the trip. Not fair. :-)

All fixed in V1.2 (7) if you accept that the elapsed time is front ended. ie the elapsed times are when you leave the waypoint and not when you get to it.

![image](https://cloud.githubusercontent.com/assets/283364/25460210/1d8c77a2-2a97-11e7-9714-faf57fff0a9b.png)

**Comment by EVGrokker** [comment]
Nice. This trip and associated tutorial really show off the power of the app nicely.
