### ISSUE TITLE
Change Charger Types for Regions

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#331]
Need to do a bit of research on the charging rates.

**Comment by aesculus** [comment]
> Here in Austria we use for destination charging: - Standard socket 10A (we call it "Schuko" which stands short for Schutzkontakt) which is mostly 2kW - one phase 16A (3,7kW) - three phase CEE 16A (11kW) - three phase CEE 32A (22kW)

**Comment by aesculus** [comment]
Basically we need to exchange the NA charger types for other region variants when the user selects another region. This will involve the server logic too since it uses charger characteristics to determine charging time.

This will not be an easy fix.

**Comment by EVGrokker** [comment]
This seems like a V2 enhancement.

**Comment by aesculus** [comment]
Yeah, from a NA perspective. :-)

**Comment by EVGrokker** [comment]
And an installed base perspective.

**Comment by EVGrokker** [comment]
Here's an approach that could provide a workaround for different voltage/amperage combinations in other countries.

Have a switch between 'basic' and 'advanced' charger selection. The 'basic' group would be the single list picker of charger options you have today. 'Advanced' would switch to a dual numeric control arrangement, with a voltage field and an amperage field. The user would key in their unique combo. EVTO doesn't need to know what that combo is called in their locality. They save the waypoint as a favorite, and now they have Mom's _Schutzkontakt_ connector available with accurate metrics and you can do accurate computations on the available power.

I haven't given any thought to what the switching UI would look like, but it wouldn't be too hard. If this seems like it has some traction, I can mock something up.

**Comment by aesculus** [comment]
EVTO needs to know the charging rate. But the problem is that some of the chargers (esp Level III) are not linear so you need to know where you come in and where you leave.  

So if I knew the charging rate algorithm I would be good. That needs to be researched for these other chargers.

**Comment by EVGrokker** [comment]
Do you know the charging rates for NEMA 5-15, 5-20, 14-50? Can you infer the charging rate for different voltage/amperage combos from those? His list is quite far from level 3 chargers - they'd all be painfully slow by our standards. And even an approximation of the sweet spot rate (between 20-80% SoC) would be better than nothing.

**Comment by aesculus** [comment]
I have this table I built:
	ev_connector_type = {
		'NONE' : {label:'No Charger', map_label: ' ', kw:0},
		'TESLA' :	{label:'Tesla Superchargers', map_label: 'S', kw:120},
		'J1772COMBO' : {label:'SAE J1772 Combo (Level 3)', map_label: l3,kw:90},
		'CHADEMO' :	{label:'CHAdeMO (Level 3)', map_label: 'C', kw:45},
		'HPWC' : {label:'Tesla HPWC (Level 2)', map_label: 'H', kw:19},
		'J1772' : {label:'J1772 (Level 2)', map_label: 'J' , kw:19.2},
		'NEMA1450' : {label:'NEMA 14-50 (Level 2)', map_label: l1, kw:9.6},
		'NEMA520' : {label:'NEMA 5-20 (Level 1)', map_label: l1, kw: 1.6},
		'NEMA515' : {label:'NEMA 5-15 (Level 1)', map_label: l1, kw:1.4},
	};
I could add a region column to it. Note even though I have kw rates for the Level 3's, they get a special curve in EVTO calcs. Those are just placeholders for the max.

**Comment by aesculus** [comment]
My suggestion for all these EU folks was to deal with it until I had time to work on real values. I told them to go find a close equivalent and use that when necessary.  One person threatened to hold back my $2.99 PRO fee until such a time that I supported it. :-(

**Comment by EVGrokker** [comment]
The formula for kW for a given volt/amp combo is:
Voltage * Amperage * .80. The .80 derates the circuit. Let's take NEMA 14-50 as an example. 
240 volts * 50 Amps * 0.80= 9.6kW (The 0.80 derating is because you're not supposed to draw more than 80% of a breaker's rating on a constant basis, according to NEC code.)

> Standard socket 10A (we call it "Schuko" which stands short for Schutzkontakt) which is mostly 2kW - one phase 16A (3,7kW) - three phase CEE 16A (11kW) - three phase CEE 32A (22kW)

Suppose he had the Advanced Volt/Amp fields available to him. 
For his lowest power outlet he'd input 240V (typical for Europe), 10A: 240 * 10 * 0.8 = 1.92kW, which he referred to as 2kW. Pretty close.
For his one-phase 16A outlet: 240 * 16  = 3.84kW (he's not derating that one)
I don't know the voltages for the CEE circuits, but the math's going to be consistent. This is a viable workaround without country-specific coding on your part. 

I'd bet if you ask those folks who've contacted you about this if being able to input volts and amps as a short-term solution would be adequate, they'd welcome it.

But it would still be farther down the feature list :)

**Comment by EVGrokker** [comment]
Not to beat this to death, but I just realized there's an even simpler solution. 
>Standard socket 10A (we call it "Schuko" which stands short for Schutzkontakt) which is mostly 2kW - one phase 16A (3,7kW) - three phase CEE 16A (11kW) - three phase CEE 32A (22kW)

In all cases, he's providing the kW of the connection. The advanced mode could simply be a simple numeric entry box where the user inputs the available kW of the charger. We could provide some guidelines in Help for computing available kW.

**Comment by aesculus** [comment]
Well if there are only three then why don't we just do the three and call it?

I think it's more of wanting an appropriate choice than 100% accuracy.

**Comment by EVGrokker** [comment]
This is actually a perfect opportunity to address another issue that I haven't written up yet that affects all regions.

Consider the US market. The picker lists the most common charging options. But there are other charging options. For example, 240v 30A dryer outlets are commonly used by Tesla owners staying as a guest at someone's house. And people also use 14-50 outlets at RV campgrounds, but dial back their charging amperage so they don't blow the circuit breaker, or because they're dragging a trailer than they need to plug into the same circuit.

For example, here's a quote from Jim Vandegriff [on a thread about towing with an X](https://teslamotorsclub.com/tmc/posts/2078620/):
>Our campground - we were just able to plug into the 50 amp circuit (dialed down to 27 amps in the car because we also plug in our Airstream on the 30 amp circuit) because the location of the electrical box made the cord stretch.

So this is a golden opportunity to add the ability to support less-typical charging numbers.

Let's add a item to the bottom of the picker, 'Custom'. Selecting Custom enables a numeric input field where you can enter the kW available. That supports folks in foreign countries with unfamiliar outlet configurations, it supports folks in the US charging at Mom's house. It's not the ideal solution for every circumstance, but it gives your a perfectly reasonable placeholder until such time that you can address the detailed charging possibilities in every country.

![custom charger](https://cloud.githubusercontent.com/assets/26678403/25800457/afae29f6-33a6-11e7-9f58-c2d1c5373385.png)

This could also be a nice opportunity to expose the default charging level for each of the other standard picker selections. For example, if the user picks HPWC, the kW field would display 19, but the field would be uneditable, so the text would be in gray.  The downside to that is that the displayed level would be the maximum for that type of charging connection, but not necessarily the power that the user's car would be charging at. For example, the 19kW number you use for HPWC assumes a 100A breaker, and a car capable of charging at 80A. My HPWC is wired at 50A, so I the most power I ever get at home is 208 * 40 * = 8.3kW. (I'm on a three-phase circuit, hence the 208V). So that's a perfect opportunity for me to establish that my Home favorite has a custom charging level. We'd explain in the help text that the displayed kW number is the max for that type of circuit, and their actual charging rate would depend upon many other factors.

**Comment by EVGrokker** [comment]
Here's another example of an unfamiliar charging scenario from [a TMC user in Switzerland](https://teslamotorsclub.com/tmc/posts/2087156/):
>I have underground parking here in Switzerland. It is very, very common. Along with running 400v triple phase to my two parking spots,

**Comment by EVGrokker** [comment]
[Another TMC discussion on charging options in Australia](https://teslamotorsclub.com/tmc/posts/2149703/).

**Comment by aesculus** [comment]
What about this sort of simplified version of charging that is not perfect but close enough for all regions.

![image](https://user-images.githubusercontent.com/283364/27263693-a4a98af8-5423-11e7-8b72-1568a3926093.png)

**Comment by EVGrokker** [comment]
I think that adding these charging options is a good idea and should pacify the 'outside NA' crowd. 

But my earlier comments about needing to also support custom charging levels stands. Inevitably someone will ask for it. Having it will cover any circumstance while you evaluate whether a new standard should be added to the list.

**Comment by aesculus** [comment]
It's boils down to this under the covers:
- Everything is based on kWatts delivered
- The charge rate is either linear or is derived by some mathematical model involving the charging infrastructure and/or the battery state

So a bespoke method that is linear is no big deal. One that uses a different curve is not an option for bespoke.

Right now the chargers are broken down into three categories:
- Low power (Level 1) AC chargers that are linear and aren't affected by the state of the battery or car chargers 
- Mid power (Level 2) AC charging that is linear and tempered by the charging infrastructure (ie > 11kW) but not by the battery state. Mostly affected by the power output of the chargers and the type of chargers in the car 
- High powered  {Level 3) DC charging that is not linear, has some cryptic curve that is related to the state of the battery in the car. I use a 3rd order polynomial curve for these (SC, JCombo and Chademo)

**Comment by EVGrokker** [comment]
I'm comfortable with telling users that specifying a custom level will be applied linearly without charging tapers. In almost every case I can think of, the custom rate is because they're dialing it down for some reason. We could limit the highest level that can be input for a custom charging level.

**Comment by aesculus** [comment]
For now I am going to go with this list. If they cannot find something close then so be it. We are already splitting hairs here.

![image](https://user-images.githubusercontent.com/283364/27299784-5b9278c4-54e2-11e7-9a5a-cb797cc2fcb4.png)

**Comment by EVGrokker** [comment]
OK

**Comment by aesculus** [comment]
The trick with these Level 2 chargers that are higher than 11 kW is that the car charger will set the max value.
<table>
<tr><th>Charger (amps)<th><th>Divisor of Time<th></tr>
<tr><td>40<td><td>1<td></tr>
<tr><td>48<td><td>1.2<td></tr>
<tr><td>72<td><td>1.45<td></tr>
<tr><td>80<td><td>2<td></tr>
</table

I let you try to explain that in the help. :-)

**Comment by EVGrokker** [comment]
I'm closing this issue as implemented.

**Comment by aesculus** [comment]
I

**Comment by aesculus** [comment]
Version 1.2 (50) has a generic based charging time algorithm that is based on the in car charging capacity applied the regions max Level 2 rate.  If the connection is higher than the car's capacity it will be limited by the car.

This means only the Level 3 chargers use the more complex algorithms and all other charging is based on the regional max and the car's percentage of that max (Model S with dual chargers is currently the max).

Going forward then it is easy to add any additional Level 1 or 2 chargers as the only requirement will be what region (there are really only two areas - NA and other), and the EVST capacity.
