### ISSUE TITLE
Consider Different Shape for Non Assigned Charger Icons

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#343]
A user complained that they could not tell a allocated charger from an waypoint because of the similar shape. I offered to change the color but they felt a different shape would be better. Something to consider.

**Comment by EVGrokker** [comment]
This is a good suggestion.

I'd propose a shape that borrows the outline of a supercharger. 

![supercharger-station](https://cloud.githubusercontent.com/assets/26678403/25554665/fd0eff90-2c8f-11e7-9eb3-ea1b06055550.png)

Referencing the size and shape of a waypoint pin, by simply squaring off the sides and interior of the top, but retaining the pointed 'pin' bottom, that should be enough visual distinction to separate a charger from a traditional waypoint. You would still have enough space for the letter designation. And there's enough room for color coding.

Here's a crude approximation of what I have in mind, sort of like a popsicle stick shape with a pointed bottom, and an interior like the interior of the supercharger:

![schargerpin](https://cloud.githubusercontent.com/assets/26678403/25554800/30593998-2c94-11e7-91ad-77fa3d0f9632.png)

**Comment by aesculus** [comment]
But OK to use this for all the preselected chargers (Level 1-3 etc.)?

But then it begs the question if this shape would follow the charger after it was selected, and then we are right back into it again.

I originally proposed a bright pink color to differentiate selected vs unselected. The OP thought that would be an issue in case they overlayed each other. But waypoints always overlay chargers so that should not be an issue.

**Comment by EVGrokker** [comment]
My opinion is that the shape works for all charger types, before and after selection. I would not mess with color assignments at all, as that will interfere with SoC reporting. Keep the current color meaning, simply change the shape of charger icons regardless of whether they're part of the route or not.

**Comment by aesculus** [comment]
>Also a suggestion, which something you mentioned leads me to believe you may already be working on this: the icons for a stop at a random waypoint, and for a stop at the supercharger, are similar enough that it is not always obvious that there is not a supercharger there. How about a unique Icon for superchargers? 

>Several times I found myself looking at a route believing that I would have sufficient energy, only to realize that some of my way points in fact did not have supercharging.    If the icons been visually different enough, I likely would not have made that incorrect association.

>I had attempted a route from Cheyenne Wy to Salt Lake City, UT.  You correctly routed me down through Denver and I70 because there are currently no SCs on the shorter I80 route.  But when looking at the I80 route, where I had put in some manual waypoints, I initially believed those waypoints were SCs, not because they had the little A as in automatically chosen, but because they had the "right shape" and I mistakenly believed they were SCs.  Perhaps a case of seeing what I wanted, rather than what was there, but this did "get me" several times on different routes.

I would have thought the big S would have been enough but apparently not. I am worried that if we did change the shape, there could still be confusion about whether there was a charger actually selected vs one shown from the toggle. Hence why I mentioned the bright color to differentiate a selected charger vs non selected.

**Comment by EVGrokker** [comment]
I think there are already too many colors. And many users (myself included) have trouble differentiating colors.

I think that using a different shape for charging waypoints solves this problem elegantly. I wish I would have thought of it. :)

**Comment by aesculus** [comment]
OK. To recap:

All chargers (SC, HPWC, Level 1-3) will get this new shape for both within trip and not in a trip. The non charging waypoints will stay as regular pushpins?

**Comment by EVGrokker** [comment]
Yes.

Another way of saying it is that we're updating the appearance of all charger pins to a popsicle or tombstone shape. All other waypoints retain their original balloon shape.

**Comment by aesculus** [comment]
OK. Sample soon

**Comment by aesculus** [comment]
How about this: Color, letter fill and (A) added appropriately.  This would be the generic non selected charger icon. The others would have the three colors and white border.


![charger-marker-not-selected](https://cloud.githubusercontent.com/assets/283364/25558264/ed3d6a82-2cd7-11e7-8939-329351dd7194.png)

**Comment by EVGrokker** [comment]
You are an artist. Looks great.

**Comment by EVGrokker** [comment]
I would flatten the interior white space, I.e. don't follow the upper exterior curve. This would mimic the Tesla interior shape.

**Comment by aesculus** [comment]
Lets try this one.
![charger-marker-not-selected](https://cloud.githubusercontent.com/assets/283364/25558552/06c6b322-2cde-11e7-84e1-96cc4115d2ea.png)

**Comment by EVGrokker** [comment]
I am happy. I will shut up now.

**Comment by aesculus** [comment]
I have both red and green versions of the above icon. Red for SC's for sure. Green for non Tesla chargers.

Should the Tesla HPWCs be red or green?

**Comment by EVGrokker** [comment]
My instinct is that there should only be one design for all chargers, but I'm willing to see what the red and green versions look like in context.

Here's my reasoning: We already have two visual design cues with charger pins. They will be labeled with the 'S', 'H'… letters that identify the type. They will also be colored with the anticipated SoC upon arrival. Adding another color cue that competes with the SoC color coding will be confusing. And, it will be redundant because of the identifying letter.

If you want to try it in a beta release so we can see what it looks like, let's do it. To answer your question, I would encode HPWCs with the second group (green), since superchargers are in a class by themselves (Level 3). Arguably, if you were going to color code different chargers, I'd code by Level 1/2/3. 

Let's see what it looks like in context.

**Comment by aesculus** [comment]
I think you will find it OK. It's only the unselected chargers. Very subtle.  Green for non Tesla plugs and red for Tesla plugs is how I see it.

The version (9) you get will not have red for NREL Tesla chargers.

**Comment by EVGrokker** [comment]
v 1.2.0 (9)

The new charger pin appearance looks excellent. Here are my suggestions:
- For unassigned chargers, I'd suggest red strokes for Level 3, green for level 2, gray for Level 1.
- Automatically assigned chargers look good in context, but I'm wishing that they had a darker stroke on the border and interior to make them look a little sharper and accentuate the new popsicle shape. In other words, imagine that the image you're using for unassigned chargers was filled in with the SoC color such that you could still see the border edges. 
- Manually assigned chargers need to use the new popsicle shape after they've been converted. See the attached image for an example, where it's still the old balloon style. In other words, charger pins will always be rendered in the popsicle shape - assigned, unassigned, required, whatever.

---

![required charging pin](https://cloud.githubusercontent.com/assets/26678403/25567910/e1e1d000-2db4-11e7-9b88-4ff7ba399391.PNG)

**Comment by aesculus** [comment]
> For unassigned chargers, I'd suggest red strokes for Level 3, green for level 2, gray for Level 1.

What's a stroke in this context.

> Automatically assigned chargers look good in context, but I'm wishing that they had a darker stroke on the border and interior to make them look a little sharper and accentuate the new popsicle shape. In other words, imagine that the image you're using for unassigned chargers was filled in with the SoC color such that you could still see the border edges.

I was surprised they came out so soft. It's exactly the same as the regular chargers. Are you suggesting I should try a 1px line around the colored parts?

>Manually assigned chargers need to use the new popsicle shape after they've been converted. See the attached image for an example, where it's still the old balloon style. In other words, charger pins will always be rendered in the popsicle shape - assigned, unassigned, required, whatever.

Clearly I did not test this as it supposed to be this way.

**Comment by EVGrokker** [comment]
>What's a stroke in this context.

I don't know how your pin imagery is managed within the app. I'll assume you have a library of pins images representing all possible combinations, then you select the appropriate pin to add to the map at the appropriate spot. 

Let's consider this sample pin that you constructed earlier in this thread:

![06c6b322-2cde-11e7-84e1-96cc4115d2ea](https://cloud.githubusercontent.com/assets/26678403/25568063/3f96a0a6-2db8-11e7-901b-bef3b3cdfc5c.png)

There are two strokes in that image, the exterior and the interior. I believe both strokes are red.

In testing 1.2.0 (9), the NREL chargers show up with green strokes, interior and exterior.

You had asked what stroke color HPWCs should be - red, because they're Tesla, or green because they're in the NREL database. My response is that the stroke color for unassigned chargers should relate to the their charging capacity - red for Level 3 (which will include ChaDeMo), green for Level 2, gray for Level 1.

>I was surprised they came out so soft. It's exactly the same as the regular icons. Are you suggesting I should try a 1px line around the colored parts?

Yes. I think what would be most effective would be a border around the colored parts that's a darker shade of the interior color. For example, a darker green border with a green pin, darker red border with red, etc. Also, I'd try the same darker stroke on the interior edge as well. The end result would look like you flooded the unassigned charger pin image above with the appropriate color. The interior white is still white (for the type key) and the borders defining the exterior and interior edges are still visible.

**Comment by aesculus** [comment]
Can you doctor up a sample? I understand what you mean by a stroke now, the 2px border in red above.

I need the unassigned push pins to stay very noticeably different from the ones that are part of the route and have color depicting their reachability.  So unless I am misunderstanding what you want, I don't want to add more color to the unassigned charger pins.

**Comment by EVGrokker** [comment]
That's a 1px stroke around the outer and inner edges at 50% brightness. The interior green is about 66% brightness. That's the general idea.

<img width="44" alt="green poposicle" src="https://cloud.githubusercontent.com/assets/26678403/25568236/9793d258-2dbb-11e7-8f5c-09a042862071.png">

With respect to the unassigned pins, what is the color code you're using to depict reachability? Maybe I was misunderstanding what I was seeing.

**Comment by aesculus** [comment]
All unassigned pins are white. They just have the stroke color red (Tesla) or green (non Tesla).  The sample way above in white is an unassigned charger pin.
![charger-marker-not-selected-green](https://cloud.githubusercontent.com/assets/283364/25568271/dc82c750-2db3-11e7-840c-d568d200b38e.png)
![charger-marker-not-selected-red](https://cloud.githubusercontent.com/assets/283364/25568270/dc80c770-2db3-11e7-99ac-387830f82944.png)

**Comment by aesculus** [comment]
I can add the 1px dark gray around the edges. Note there is some shading on both the exterior and the interior for the pins. That might be adding to the softness. This was always there on the regular pushpins

**Comment by EVGrokker** [comment]
I do see that the balloons are soft, but it's less of an issue visually because of their round shape -a softer shape. The popsicles need help. Shading will be fine if the border color creates edge definition.

With respect to unassigned charger pins, let's describe them this way: The interiors are white, meaning they're unassigned (and thus have no reachability coding). Their border color tells you what kind of charger they are. You're using red to represent Tesla Superchargers, green for everything else, correct?

My proposal for the meaning of red/green unassigned chargers (with white interiors) is that red = Level 3 chargers, and green = Levels 2 and 1. 

The reason I'm suggesting this is that I believe that a Level 3 ChaDeMo charger has the potential to charge at a faster rate than any level 2 charger, so if you or I were contemplating where to charge in the absence of a supercharger, we'd pick a Level 3 ChaDeMo over a Level 2 anything purely for speed.

I don't have real-world experience with this planning scenario. I could be making this up. And it's perfectly acceptable to say "90% of EVTO users want to get from supercharger to supercharger, the rest of the charger database is far less interesting, including HPWC. Let's use the color coding to help them stay in the supercharger lanes." 

I'd be fine with that. In that case, I'd say that HPWCs are coded green, because they're slower.

**Comment by EVGrokker** [comment]
>I can add the 1px dark gray around the edges. 

Note that my rendering was not gray, it was a darker value of the green.

**Comment by aesculus** [comment]
> The reason I'm suggesting this is that I believe that a Level 3 ChaDeMo charger has the potential to charge at a faster rate than any level 2 charger, so if you or I were contemplating where to charge in the absence of a supercharger, we'd pick a Level 3 ChaDeMo over a Level 2 anything purely for speed.

I am thinking more adapter type. If your are Tesla owner and have not bought any adapters other than what came with the car, you are most likely going to want to know which ones my car can use directly (without an adapter) and which can be used only with an adapter. Also you can think of it another way.

The red ones are generally free and the green ones usually have a fee.

**Comment by EVGrokker** [comment]
OK, let's leave it as is.

**Comment by aesculus** [comment]
I will put the darker highlighting on them later. So that way we both win. :-)

**Comment by aesculus** [comment]
Here is a sample of the green manual charger icon. I removed the white 2px border and added a 50% dark value 1px border around the entire green area. It seems less fuzzy.

![test](https://cloud.githubusercontent.com/assets/283364/25583984/feec85f2-2e48-11e7-9bf7-ab9b5ce9a0f2.png)

**Comment by aesculus** [comment]
Here it is with a 2px wide borders.
![test](https://cloud.githubusercontent.com/assets/283364/25584085/810db31c-2e49-11e7-8935-42c648fc1d90.png)

**Comment by EVGrokker** [comment]
Looks sharp! I like it.

**Comment by aesculus** [comment]
Which one?

**Comment by EVGrokker** [comment]
To me, the second one seems cleanest. The first one is definitely an improvement as well, but I vote for 2px.

**Comment by aesculus** [comment]
Of course I went with version 1. The other looked a bit too sharp to me. If it does not look good after seeing it for a day or two, I can bump it up to a 2px border.

**Comment by EVGrokker** [comment]
It looks good. Let's go with your choice.

**Comment by aesculus** [comment]
I reopened this because we never updated the help file to explain these icons and their meaning (ie green vs red)

**Comment by EVGrokker** [comment]
Issue #411 updated to mention red charging pins.
