### ISSUE TITLE
Supercharger overlay behavior

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#358]
What is the expected behavior when displaying a route, then toggling the Supercharger overlay on?

Currently, it looks like the entire (continental) database is shown. Is that correct?

It seems that the behavior for SC overlays and NREL overlays (#342) should be consistent.

![sc route](https://cloud.githubusercontent.com/assets/26678403/25614882/43e6b508-2ef1-11e7-9502-cd71d8f84cfc.PNG)

**Comment by aesculus** [comment]
Yes. Currently the SC (and HPWC) chargers are shown for the geography in settings, not based on the map extent or route or some other refinement.

The NREL charger access has some issues in the way they fetch chargers and the means to determine area. It's by no means consistent and I cannot load all of their data into the app (legally and performance wise). So I have to fetch it each time a user wants to see it. Plus bw and speed limitations dictate a smaller subset than everything they have. The supercharger db, even for Europe, is small comparatively, so little performance impact to the app to show them all.

This is not the case with the Tesla chargers (note I said Tesla because NREL does not catalog HPWC for some reason but does SC, which I never ask for). Another reason I wanted the red vs green icons. And this is why I have an issue today with the Filter not doing HPWC. (issue #332 )

**Comment by aesculus** [comment]
I added the feature to have the Charger Filter toggle HPWC on/off and to display them or not when the user selects the Tesla Charger icon from the map. Added in V1.2 (22)

**Comment by aesculus** [comment]
There is still an open issue here in at least one instance. If a user enters a supercharger at the same location as a preconfigured Tesla Supercharger, they can actually have two chargers at the same location.

This is rare but I have seen it before. Perhaps this should have it's own issue?
