### ISSUE TITLE
Invalid Destination Addresses and Choosing Locations

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#367]
Some users are frustrated because if they enter, or copy/paste, and invalid address, the app keeps prompting them for a location.

They believe they entered a correct address even though they never selected one from the list. This shows two issues:
- Copy/Paste works well, but only if the address is valid.
- Many users are do not understand that you must select a valid location before you can save a location based dialog.

**Comment by EVGrokker** [comment]
3-part solution:
1) Add help text explaining how addresses need to be verified by Google.
2) If an error is detected when user touches Calculate before a valid origin/destination pair is entered, show the error dialog, but return them to the New Trip dialog so they have a chance to correct it.
3) Enhance behavior of the New Trip dialog to show when a field has been validated. For example, in the dialog below, the **Origin** field '1234 Nowhere' has not been validated by Google, so the magnifying glass icon is still present. The **Destination** field, '123 Main' has been validated by Google, so the magnifying glass is replaced by a checkmark. If user clicks the 'x' to reset the address field, the magnifying glass is restored until they select a new validated address.

---

![newtrip](https://cloud.githubusercontent.com/assets/26678403/25967448/65047c28-364b-11e7-8588-940adbd04358.png)

**Comment by EVGrokker** [comment]
Better icon option: Instead of the checkmark replacing the magnifying glass, use the pin icon in the Google results list. Then it looks like the pin "jumped" from the results list to the Origin/Destination field when validated.

**Comment by aesculus** [comment]
I will give the icon thing a try.

**Comment by aesculus** [comment]
I did some research and experimentation on this. It's doable but not easy to hack the icon. And I have to worry about resetting it etc.  We can keep this open until I get bored. :-)

**Comment by EVGrokker** [comment]
With respect to point 2 above, validating both Origin and Destination before leaving the dialog… I'd suggest the following:
- When user validates an address, set a flag `origin_validated` or `destination_validated`. 
- When user touches Calculate, if both flags are not set, display a dialog similar to the New Trip error dialog, telling user that both origin and destination addresses must be selected from the popup list of matching results before the trip can be calculated. The New Trip dialog stays up with its contents intact.
- Obviously, if user edits an input field, either by changing or deleting its contents, the respective flag would be cleared.
- The only way to exit the dialog to begin calculating the trip is with a validated origin/destination pair.

**Comment by aesculus** [comment]
All the above but the icon has been addressed in V1.2 (12) for New Trip, Edit Segment Details, New and Edit Waypoint.

**Comment by EVGrokker** [comment]
v 1.2.0 (12)
A couple of observations about New Trip dialog error handling:

- I've noted alternative popup text content, depending upon conditions in the table below.
- When you display the error popup, it can only be dismissed by tapping within in. Is it possible to dismiss the error popup on any press? For example, the user might go directly to the input field to continue typing or touch an item in the displayed list of results, neither of which dismiss the popup.
- I know we have an active proposal to change the icon in the Origin and Destination fields when an address has been validated. As an alternative, would it be easier to switch the field from normal to bold upon validation?  (And back to normal upon editing or clearing the field.) This might be adequate.
- If Location Services is disabled, the dialog always fails to Calculate, even when Origin and Destination are both valid. See second table below.
- Question: When Location Services are enabled, there's an odd logic to the Origin field. If they type something there, it needs to be validated. However, if they type nothing, the user's current location is assumed. It would be nice to clarify what's happening. Instead of Origin, how about displaying Current Location (in gray) in the origin field. If the user wants to change it to a specific origin, they touch in the field and start typing. Upon clearing any content from that field, it would go back to Current Location.

When Location Services is **enabled**, I observe the following behavior:

<table>
  <tr>
    <th>Origin</th>
    <th>Destination</th> 
    <th>Result / Suggested text</th>
  </tr>
  <tr>
    <td>[empty]</td>
    <td>[empty]</td> 
    <td><strike>You must enter a destination and select from the list provided!</strike><br/>
Enter an Origin and Destination for your trip</td>
  </tr>
  <tr>
    <td>Not validated</td>
    <td>Not validated</td> 
    <td><strike>You must enter a destination and select from the list provided!</strike><br/>
Select a matching address from the search results:</td>
  </tr>
  <tr>
    <td>Validated</td>
    <td>Not validated</td> 
    <td><strike>You must enter a destination and select from the list provided!</strike><br/>
Select a matching address from the search results:</td>
  </tr>
  <tr>
    <td>Not validated</td>
    <td>Validated</td> 
    <td><strike>You must select an origin from the list provided!</strike><br/>
Select a matching address from the search results:
</td>
  </tr>
  <tr>
    <td>Validated</td>
    <td>Validated</td> 
    <td>[dialog closes, trip calculates]</td>
  </tr>
</table>

When Location Services is **disabled**, I observe the following behavior: (After fixing the bug, dialog verbiage should match above.)

<table>
  <tr>
    <th>Origin</th>
    <th>Destination</th> 
    <th>Result</th>
  </tr>
  <tr>
    <td>[empty]</td>
    <td>[empty]</td> 
    <td>You must select an origin or turn location services on!</td>
  </tr>
  <tr>
    <td>Not validated</td>
    <td>Not validated</td> 
    <td>You must select an origin or turn location services on!</td>
  </tr>
  <tr>
    <td>Validated</td>
    <td>Not validated</td> 
    <td>You must select an origin or turn location services on!</td>
  </tr>
  <tr>
    <td>Not validated</td>
    <td>Validated</td> 
    <td>You must select an origin or turn location services on!</td>
  </tr>
  <tr>
    <td>Validated</td>
    <td>Validated</td> 
    <td>You must select an origin or turn location services on!</td>
  </tr>
</table>

**Comment by aesculus** [comment]
I am having a bit of issue with the text in the table logic. I may not be able to get to that much granularity but will try.

Are you saying that in every case with location services off you get an error and cannot proceed?

**Comment by aesculus** [comment]
Confirmed it

**Comment by EVGrokker** [comment]
If you need to make the [empty][empty] the same as the other errors, that's fine. Notice that I actually used the same error text in every other case, since the popup appears above the offending field.

>Are you saying that in every case with location services off you get an error and cannot proceed?

Yes, that's the case. If Location services disabled, nobody's going anywhere.

**Comment by aesculus** [comment]
>Question: When Location Services are enabled, there's an odd logic to the Origin field. If they type something there, it needs to be validated. However, if they type nothing, the user's current location is assumed. It would be nice to clarify what's happening. Instead of Origin, how about displaying Current Location (in gray) in the origin field. If the user wants to change it to a specific origin, they touch in the field and start typing. Upon clearing any content from that field, it would go back to Current Location.

Right now it says My Location as a gray placeholder. Do you actually want the address that has been geolocated in gray?

**Comment by aesculus** [comment]
>I know we have an active proposal to change the icon in the Origin and Destination fields when an address has been validated. As an alternative, would it be easier to switch the field from normal to bold upon validation? (And back to normal upon editing or clearing the field.) This might be adequate.

Can't really change the UP input dialog font weight. I will do the icon later.

**Comment by EVGrokker** [comment]
> Right now it says My Location as a gray placeholder. Do you actually want the address that has been geolocated in gray?

My mistake, I had location services turned off.  All good.

**Comment by aesculus** [comment]
OK. All of this except the icon is fixed in V1.2 (14)

**Comment by aesculus** [comment]
I fixed this message in a continuation trip too if you try to go to the same location.
