### ISSUE TITLE
Change Layout for Current/Archive Trips Panels on Smaller Devices

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#388]
For phones often the layout of the trip lists are hard to visualize. The info is spread across the screen rather than in a familiar list format. It would be better if the list items were condensed into one line, while still retaining the same functionality of selection.

**Comment by aesculus** [comment]
This has been added to V1.2 (23)

![image](https://cloud.githubusercontent.com/assets/283364/26499315/f4c1d7e2-41e6-11e7-96fc-c033ab7ca3a4.png)

**Comment by EVGrokker** [comment]
Nice.

**Comment by EVGrokker** [comment]
Comments:
- The drama masks are a placeholder for a thumbs up/thumbs down rating. How about making them touchable, which would display a popup to assign the rating. Alternatively, touching that spot would cycle through the ratings (none/up/down).
- It seems that you revised the text and layout since posting the initial image in the comment above. Here's what I'm seeing in 1.2.0 (23):

![img_0568](https://cloud.githubusercontent.com/assets/26678403/26549666/fb7514a6-442e-11e7-9254-16636c93770d.PNG)

- I prefer the proposed layout to the implemented layout. 'Duration' and 'Efficiency' seem unnecessary. The proposed layout was much cleaner and clearer.
- I find 'Plan' to be redundant with assigning a rating. A user would know if they've taken the trip, and if they've assigned a rating, it means that they've reacted to it. I'd propose dumping Plan/Taken.

**Comment by aesculus** [comment]
The drama icon was to show that the trip was not rated yet.  I am OK with another icon to show that state.  I considered a gavel for example.  As seen in the Status dialog you can switch from plan/taken without taking action on rating the trip.

**Comment by aesculus** [comment]
Duration and Efficiency are wacked not in V1.2 (24).

**Comment by EVGrokker** [comment]
Note suggestion in #395 to change drama icon to a gavel icon.

**Comment by aesculus** [comment]
Do you want gavel or scale? #395 shows a scale. I you want a scale we will have to find something else for Optimize Route. 
![754-scale 2x](https://cloud.githubusercontent.com/assets/283364/26683885/2efa0896-469a-11e7-869f-44c86fc6dd94.png)
![782-compass 2x](https://cloud.githubusercontent.com/assets/283364/26683927/57f023f2-469a-11e7-8803-da7dd9cdd0ea.png)
![996-gavel 2x](https://cloud.githubusercontent.com/assets/283364/26684018/a7523a2a-469a-11e7-9326-86d3ecb736a9.png)
![938-connections 3x](https://cloud.githubusercontent.com/assets/283364/26684051/c3f0f31a-469a-11e7-83e5-defde7c90f43.png)

**Comment by EVGrokker** [comment]
Gavel
