### ISSUE TITLE
My Cars dialog: Temperature display, limits

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#444]
v 1.2.0 (37)

When the Climate Control checkbox is unchecked, the temperature digits should be rendered in gray suggesting inactive.

Also, should there be an acceptable range of values for this field, based on units in use? For example, fahrenheit temps might be from 60º to 80º? And celsius might be from 15º to 27º? Extreme or negative values should be disallowed.

**Comment by aesculus** [comment]
First the easy part. I don't seem to have much control over what gets typed in. If you use the slider it will keep you from entering a negative number.  I could do something after leaving focus (ie remove negatives and cap a value at a max for the region setting. 

Interestingly this should probably occur as I am guilty myself of such a situation. The app does everything in MKS and I usually work in that mode (ie metric) so it's easier to spot issues.  Sometimes I have brained out and put in 75 for the temp not remembering I was in metric. That is 167 C.  The energy requirements of keeping your car that hot will pretty much stifle any efficiency in your car. :-)

The other part may need a discussion.  If we disable the text input because the checkbox is not checked, it will require the user to uncheck it before they set a standard value.  Remember that we still use the temp while charging, even when unchecked.  I think it should never be disabled because of that.

**Comment by EVGrokker** [comment]
My experience with edit controls in other contexts is that they often utilize masks that limit the type of content that can be keyed in, for example numbers only. And if it's a numeric input field (as this one is), some native controls also offer the ability to limit the input to a certain range.

If those constraints are not available with your UI package, so be it. Not a big deal.

>If you use the slider it will keep you from entering a negative number. I could do something after leaving focus (ie remove negatives and cap a value at a max for the region setting.

I don't think this enhancement clears the bar at this time. Most users will set and forget.

>The other part may need a discussion. If we disable the text input because the checkbox is not checked, it will require the user to uncheck it before they set a standard value. Remember that we still use the temp while charging, even when unchecked. 

In my experience, grayed-out text in an edit control always suggests a value that is set, but inactive at the moment. My suggestion was based upon my expectations of a grayed-out control. It you want to leave it editable even when the checkbox is unchecked, I'd suggest not graying it out, which communicates to the user it's still editable.

**Comment by aesculus** [comment]
>In my experience, grayed-out text in an edit control always suggests a value that is defined, but inactive at the moment. My suggestion was based upon my expectations of a grayed-out control. 

But it is not inactive for all scenarios, just the driving one.

>It you want to leave it editable even when the checkbox is unchecked, I'd suggest not graying it out, which communicates to the user it's still editable.

I am confused by this statement. If the checkbox is not checked the textbox is naturally editable and not gray. I think we are debating making it disabled and therefore gray and uneditable when the checkbox is not set. I was just advocating for never making the textbox disabled.

**Comment by EVGrokker** [comment]
Close enough. You're advocating for never making the numeric input field disabled, even when the Climate Control checkbox is unchecked, and I can live with that.

**Comment by aesculus** [comment]
OK. Fixing the input range thing now.

**Comment by aesculus** [comment]
For your info: temp range is Lo 60-81 Hi in degree F.  Had to go the friggin car to find out.

Not sure what Lo and Hi equate to.  I guess I can make our range 55-85 and call it.

**Comment by aesculus** [comment]
You are getting your wish for a selector for cabin temp.

**Comment by aesculus** [comment]
The Edit Trip Details and My Cars cabin temp are now selectors in V1.2 (38).
