### ISSUE TITLE
Current Trips terminology

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#466]
Comments about 'Plan(ned)' and 'Taken':

- If you want to use 'Plan' as the partner to 'Taken', it should be 'Planned'. The test I apply is "The status of this trip is [try both terms here]." 'Plan' doesn't work, but 'Planned' does. There is inconsistent use of 'Plan' and 'Planned'. For example, in the Current Trips dialog, the Group By Status uses 'Plan' in the header.
- Consider the use of 'Planned' and 'Completed'.

**Comment by aesculus** [comment]
Where I got stuck with Plan and Taken was with the tablet format since it's the column label. With the new phone layout we don't see these words at all.

So I am good with changing to Planned/Completed with the phone and in the collapsible headers, but need to come up with a short equivalent for the tablet layout column header.

**Comment by aesculus** [comment]
Implemented in V1.2 (41)
