### ISSUE TITLE
Real world trip data: Model X90D w/22" tires

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#468]
[From TMC user @puregreddy](https://teslamotorsclub.com/tmc/posts/2118040/):

Just completed my first trip from Irvine to the East Bay Area and back this past weekend: (May 20 or 21, 2017)

Northbound-
- First leg to Tejon Ranch = avg 382 wh/mi
- Second leg to Harris Ranch = avg 411 wh/mi
- Third leg to Gustine = avg 414 wh/mi
- Final leg to east bay = avg 422

Southbound-
-First leg to Gustine = avg 366 wh/mi
-Second leg to Harris Ranch = avg 437 wh/mi
-Third leg to Tejon Ranch = 425 wh/mi
-Fourth leg to Culver City = 316 wh/mi
Final leg to Irvine = 360 wh/mi

This is a X90D with 22" wheels, new tires (5K miles on them). Range mode off and AC set to 74 the entire trip. Autopilot used rarely (10% of the time) and I tried to keep my speed between 75 and 80 mph. And I probably stopped a little too often as this was my first real "long" trip. 

Was pretty windy out there as gnguyen posted, the X can get pushed around quite easily. The third leg heading southbound shows my highest wh/mi average......I was on the throttle quite heavy that leg as my daughter was getting anxious to stop and I was hungry. I would guess that leg probably averaged closer to 90 mph.

**Comment by aesculus** [comment]
90mph. Keep me off the highway. 

Need to know date and time.

**Comment by EVGrokker** [comment]
I inferred the date from his post (May 20-21). Time: I'd guess a morning departure.

(I didn't communicate with him, just grabbed his data from a thread.)

**Comment by aesculus** [comment]
So you think May 20-21 was the totality of his trip? Just an out and back?  I thought he didn't know what date. :-)

**Comment by EVGrokker** [comment]
He posted on May 24th, and wrote:
>from Irvine to the East Bay Area and back this past weekend:

I looked at a calendar to determine that he drove on May 20-21, and added that to the initial post.

**Comment by aesculus** [comment]
OK. Here you go. Copy into your favorite spreadsheet and let me know how close we are:

"Oakland CA Segment - May 20, 2017 8:00 AM"
"My Model X: X90D, Charger: 48, Wheels: 22, Tires: 1, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100"
"Cabin: 75°F, Power Factor: 0, Speed Adjust: 10, Payload: 220lbs"

"Instructions","Duration (secs)","Speed (mi/hr)","Length (mi)","Distance (mi)","Energy (kWh)","Efficiency (Wh/mi)","Elev Change (ft)"
"Head southwest on Harvard Ave toward Alton Pkwy",53,37.1,0.5,0.5,0.2,292,7.0
"Turn right onto Main St",98,17.8,0.5,1.0,0.1,216,-12.0
"Turn left onto Jamboree Rd",72,11.7,0.2,1.3,0.1,334,5.9
"Take the ramp onto I-405 N",765,75.7,16.1,17.3,6.6,412,-28.2
"Keep left at the fork to stay on I-405 N",2612,69.3,50.3,67.6,20.6,410,1144.8
"Merge onto I-5 N",74,75.4,1.5,69.2,0.9,556,122.4
"Keep left at the fork to stay on I-5 N",77,71.7,1.5,70.7,1,679,219.4
"Keep left to stay on I-5 N",2684,76.4,56.9,127.6,21.9,385,-387.4
"Take exit 219B toward Laval Road W",25,38.8,0.3,127.9,0,138,-19.1
"Merge onto S Wheeler Ridge Rd",20,41.2,0.2,128.1,0.1,595,34.2
"Take the Laval Road exit",17,20.1,0.1,128.2,0,491,10.6
"Merge onto Laval Rd",23,13.1,0.1,128.3,0,324,2.0
"Turn right onto Dennis McCarthy DrDestination will be on the right",62,13.0,0.2,128.5,0,52,-26.5
"Charge at the Tejon Ranch Supercharger for 25 mins from 20% SoC to 76% SoC",6580,70.3,128.5,128.5,52,402,1073.0,

"Head south on Dennis McCarthy Dr toward Laval Rd",84,9.6,0.2,0.2,0.1,451,26.5
"Turn left onto Laval Rd",36,11.2,0.1,0.3,0,163,-2.3
"Turn left onto S Wheeler Ridge Rd",39,34.9,0.4,0.7,0,-29,-53.0
"Turn left onto the Interstate 5 N ramp",42,21.3,0.2,1.0,0,120,-12.3
"Merge onto I-5 N",51,79.3,1.1,2.1,0.2,159,-142.5
"Keep right at the fork to stay on I-5 N, follow signs for San Francisco/Sacramento/Interstate 5 N",4603,81.3,104.0,106.1,41.1,395,-465.4
"Take exit 325 for Jayne Ave",23,42.6,0.3,106.3,0.1,244,-2.8
"Turn left onto W Jayne Ave",172,63.3,3.0,109.3,1.3,439,158.5
"Turn right onto S El Dorado Ave",431,67.9,8.1,117.5,2.5,308,-225.7
"Turn left onto CA-198 WDestination will be on the left",93,59.2,1.5,119.0,0.6,398,62.1
"Charge at the Harris Ranch Supercharger for 15 mins from 20% SoC to 58% SoC",5574,76.9,119.0,119.0,46,386,-656.8,

"Head west on CA-198 W",311,51.2,4.4,4.4,2.3,520,495.9
"Sharp right onto CA-33 N",271,62.7,4.7,9.1,0.7,153,-450.2
"Turn left to merge onto CA-33 N/I-5 N toward Mendota/SacramentoContinue to follow I-5 NParts of this road may be closed at certain times or days",3086,81.6,69.9,79.1,27.8,398,-351.7
"Take exit 407 for CA-33 toward Santa Nella/Gustine",27,37.8,0.3,79.4,0.1,246,-0.2
"Turn right onto CA-33 N/Santa Nella BlvdDestination will be on the left",21,10.7,0.1,79.4,0,226,0.4
"Charge at the Gustine Supercharger for 21 mins from 20% SoC to 68% SoC",3715,76.9,79.4,79.4,31,390,-305.8,

"Head south on CA-33 S",9,10.7,0.0,0.0,0,241,0.3
"Turn right to merge onto I-5 N",1751,79.9,38.9,38.9,15.8,405,108.1
"Keep left at the fork to continue on I-580 W, follow signs for Tracy/San Francisco",2148,77.6,46.3,85.2,17.4,376,-70.0
"Keep right at the fork to stay on I-580 W, follow signs for Oakland/San Francisco",673,75.9,14.2,99.4,5.4,381,-112.1
"Take exit 19D toward Interstate 980/Downtown/Interstate 880",42,64.3,0.8,100.2,0.2,247,-27.9
"Keep left, follow signs for Downtown Oakland",5,66.3,0.1,100.3,0,225,-4.9
"Continue onto I-980 W",23,72.1,0.5,100.7,0.1,265,-20.0
"Take the 18th Street exit toward 14th Street",14,44.5,0.2,100.9,0.1,325,6.0
"Merge onto Brush St",17,15.3,0.1,101.0,0,229,0.6
"Turn left onto 17th St",130,11.4,0.4,101.4,0.1,233,3.0
"Turn right onto Telegraph Ave",65,5.9,0.1,101.5,0,279,2.7
"Slight right onto BroadwayParts of this road may be closed at certain times or days",26,10.1,0.1,101.6,0,195,-0.8
"Arrive at Oakland CA",4904,74.6,101.6,101.6,39,385,-115.0,

"Trip Totals/Averages",20773,74,429,429,168,391,-5,

**Comment by aesculus** [comment]
I pumped up his pf to 5 since he is obviously more aggressive. We are damn close to his actual.

I send you the trip to play with.

"Oakland CA Segment - May 20, 2017 8:00 AM"
"My Model X: X90D, Charger: 48, Wheels: 22, Tires: 1, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100"
"Cabin: 75°F, Power Factor: 5, Speed Adjust: 10, Payload: 220lbs"

"Instructions","Duration (secs)","Speed (mi/hr)","Length (mi)","Distance (mi)","Energy (kWh)","Efficiency (Wh/mi)","Elev Change (ft)"
"Head southwest on Harvard Ave toward Alton Pkwy",53,37.1,0.5,0.5,0.2,304,7.0
"Turn right onto Main St",98,17.8,0.5,1.0,0.1,227,-12.0
"Turn left onto Jamboree Rd",72,11.7,0.2,1.3,0.1,344,5.9
"Take the ramp onto I-405 N",765,75.7,16.1,17.3,6.9,432,-28.2
"Keep left at the fork to stay on I-405 N",2612,69.3,50.3,67.6,21.5,427,1144.8
"Merge onto I-5 N",74,75.4,1.5,69.2,0.9,575,122.4
"Keep left at the fork to stay on I-5 N",77,71.7,1.5,70.7,1.1,697,219.4
"Keep left to stay on I-5 N",2684,76.4,56.9,127.6,23,404,-387.4
"Take exit 219B toward Laval Road W",25,38.8,0.3,127.9,0,150,-19.1
"Merge onto S Wheeler Ridge Rd",20,41.2,0.2,128.1,0.1,608,34.2
"Take the Laval Road exit",17,20.1,0.1,128.2,0,501,10.6
"Merge onto Laval Rd",23,13.1,0.1,128.3,0,334,2.0
"Turn right onto Dennis McCarthy DrDestination will be on the right",62,13.0,0.2,128.5,0,62,-26.5
"Charge at the Tejon Ranch Supercharger for 30 mins from 20% SoC to 79% SoC",6580,70.3,128.5,128.5,54,420,1073.0,

"Head south on Dennis McCarthy Dr toward Laval Rd",84,9.6,0.2,0.2,0.1,461,26.5
"Turn left onto Laval Rd",36,11.2,0.1,0.3,0,173,-2.3
"Turn left onto S Wheeler Ridge Rd",39,34.9,0.4,0.7,0,-17,-53.0
"Turn left onto the Interstate 5 N ramp",42,21.3,0.2,1.0,0,130,-12.3
"Merge onto I-5 N",51,79.3,1.1,2.1,0.2,179,-142.5
"Keep right at the fork to stay on I-5 N, follow signs for San Francisco/Sacramento/Interstate 5 N",4603,81.3,104.0,106.1,43.2,415,-465.4
"Take exit 325 for Jayne Ave",23,42.6,0.3,106.3,0.1,258,-2.8
"Turn left onto W Jayne Ave",172,63.3,3.0,109.3,1.4,456,158.5
"Turn right onto S El Dorado Ave",431,67.9,8.1,117.5,2.7,326,-225.7
"Turn left onto CA-198 WDestination will be on the left",93,59.2,1.5,119.0,0.6,414,62.1
"Charge at the Harris Ranch Supercharger for 16 mins from 20% SoC to 60% SoC",5574,76.9,119.0,119.0,48,405,-656.8,

"Head west on CA-198 W",311,51.2,4.4,4.4,2.4,534,495.9
"Sharp right onto CA-33 N",271,62.7,4.7,9.1,0.8,170,-450.2
"Turn left to merge onto CA-33 N/I-5 N toward Mendota/SacramentoContinue to follow I-5 NParts of this road may be closed at certain times or days",3086,81.6,69.9,79.1,29.3,418,-351.7
"Take exit 407 for CA-33 toward Santa Nella/Gustine",27,37.8,0.3,79.4,0.1,258,-0.2
"Turn right onto CA-33 N/Santa Nella BlvdDestination will be on the left",21,10.7,0.1,79.4,0,236,0.4
"Charge at the Gustine Supercharger for 23 mins from 20% SoC to 70% SoC",3715,76.9,79.4,79.4,33,409,-305.8,

"Head south on CA-33 S",9,10.7,0.0,0.0,0,251,0.3
"Turn right to merge onto I-5 N",1751,79.9,38.9,38.9,16.5,425,108.1
"Keep left at the fork to continue on I-580 W, follow signs for Tracy/San Francisco",2148,77.6,46.3,85.2,18.3,395,-70.0
"Keep right at the fork to stay on I-580 W, follow signs for Oakland/San Francisco",673,75.9,14.2,99.4,5.7,400,-112.1
"Take exit 19D toward Interstate 980/Downtown/Interstate 880",42,64.3,0.8,100.2,0.2,262,-27.9
"Keep left, follow signs for Downtown Oakland",5,66.3,0.1,100.3,0,241,-4.9
"Continue onto I-980 W",23,72.1,0.5,100.7,0.1,282,-20.0
"Take the 18th Street exit toward 14th Street",14,44.5,0.2,100.9,0.1,338,6.0
"Merge onto Brush St",17,15.3,0.1,101.0,0,239,0.6
"Turn left onto 17th St",130,11.4,0.4,101.4,0.1,243,3.0
"Turn right onto Telegraph Ave",65,5.9,0.1,101.5,0,289,2.7
"Slight right onto BroadwayParts of this road may be closed at certain times or days",26,10.1,0.1,101.6,0,205,-0.8
"Arrive at Oakland CA",4904,74.6,101.6,101.6,41,404,-115.0,

"Trip Totals/Averages",20773,74,429,429,176,410,-5,

**Comment by EVGrokker** [comment]
I'm closing all issues tagged Test Cases, as they exist only for reference and are not directly involved with proposed app revisions. Locating test cases is merely a matter of selecting 'test cases' from the Labels list. They are still available for comment and updates.
