### ISSUE TITLE
Waypoint Inspector shows different arrival SoC color at 20%

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#493]
v 1.2.0 (64)

Trip: The Fess Parker A Doubletree by Hilton Resort, [6ivja2oi4e2bmav9ztvoso]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100, Payload: 156, PF: 0, SA: 0, Temp: 21 
Device Info: iPhone; CPU iPhone OS 10_3_3 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (64) 
IAP: Pro:1, Sub:1 
Location: Unknown 

When inspecting the individual auto charging stops on this trip, the color of the stops with 20% arrival SoC values varies between yellow and green:

<table>
  <tr>
    <td>Centralia</th>
    <td>55%</th> 
    <td>Green</th> 
  </tr>
  <tr>
    <td>Woodburn</td>
    <td>21%</td> 
    <th>Green</th> 
  </tr>
  <tr>
    <td>Springfield</td>
    <td>20%</td> 
    <th>Yellow</th> 
  </tr>
  <tr>
    <td>Grants Pass</td>
    <td>20%</td> 
    <th>Yellow</th> 
  </tr>
  <tr>
    <td>Mt. Shasta</td>
    <td>20%</td> 
    <th>Green</th> 
  </tr>
  <tr>
    <td>Corning</td>
    <td>20%</td> 
    <th>Green</th> 
  </tr>
  <tr>
    <td>Vacaville</td>
    <td>20%</td> 
    <th>Green</th> 
  </tr>
  <tr>
    <td>Gilroy</td>
    <td>20%</td> 
    <th>Yellow</th> 
  </tr>
  <tr>
    <td>Atascadero</td>
    <td>20%</td> 
    <th>Yellow</th> 
  </tr>
</table> 

However, the Segment Browser shows all of the 20% arrival SoC values as yellow (including the latter stops not visible in this screen shot):

![20 difference](https://user-images.githubusercontent.com/26678403/28666995-da0cc92c-7286-11e7-9c6c-387898ea1ce4.PNG)

**Comment by aesculus** [comment]
Probably a rounding error but the inconsistencies of battery and SoC abound.

In V1.2 (65) I attempted to create some uniformity.

The goal is to have all battery indicators turn red at 8%, green over 20% and yellow otherwise.

The push pins and SoC charts are a bit different. In that case red is still 8% or less but green is whatever the user has decided is the minimal arrival SoC for the waypoint (or upcoming waypoint in the case of a SoC line).  This could be confusing but I wanted to show an indicator or their comfort settings vs just Tesla values.

**Comment by aesculus** [comment]
I reloaded this trip in V1.2 (74) and all the 20% pushpin colors are now green (Settings set to 20% min SoC). The battery indicators are all yellow per Tesla.
