### ISSUE TITLE
Editing a destination name does not update the Trip Browser

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#501]
v 1.2.0 (74)

(I recall discussing this in an earlier issue, but I'm not finding it.)

- New Trip, Seattle to Fess Parker Inn (Santa Barbara), Auto
- Pin/Segment at Grants Pass Supercharger
- Add Waypoint: Tesla SC, Petaluma CA
- Segment at Petaluma
- Edit Waypoint: final destination, rename to 'Santa Barbara'

The Trip Browser still shows the original destination name instead of the edited version. Is it possible to update the Trip Browser list so that the listed segment matches any user edits to the destination name?

**Comment by aesculus** [comment]
The trip name defaults to the segment name when you create a trip. If you change the segment name, or add additional segments, the trip name remains the same.

If you want the trip name changed, you will need to do that in Edit Trip Details.

**Comment by EVGrokker** [comment]
To clarify, it's the Segment name listed in the Trip Browser that I'm focused on, not the Trip name. 

Edit Segment Details has the functionality to rename the segment, so the functionality to rename the segment is already implemented.

However, using Edit Segment Details in v. 1.2.0 (76) causes the Optimizer to hang. I'll create a separate issue.

**Comment by aesculus** [comment]
I'm not seeing this issue. I changed the segment name and it changed the Trip Browser too as well as the title in the header.

I tried it on the iPad (with no hang) and my computer (where it hung and I pressed Cancel). But in both cases the name was reset in all the right places.

>Edit Waypoint: final destination, rename to 'Santa Barbara'
>The Trip Browser still shows the original destination name instead of the edited version. Is it possible to update the Trip Browser list so that the listed segment matches any user edits to the destination name?

Changing the destination name will not change the Segment Name, by design. You have to do it via the Edit Segment Details. We did have this discussion before I think and decided that we would not change the segment name just because the destination name changed.  

A user could have called the segment Trip To Grandma's but perhaps the destination name was "Sun City" and they did not want the segment called that so they changed it.  But they were still going to Sun City.
