### ISSUE TITLE
Add other route optimization options (energy,distance, stops)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#74]
The eventual choices should include:

- Minimize Travel Time (default)
- Minimize Energy
- Minimize Distance
- Minimize Stops
- Avoid Highways

**Comment by aesculus** [comment]
But doesn't Avoid Highways, Tolls, Ferries be applied on top of the Minimize models?

**Comment by EVGrokker** [comment]
Good point, it is a modifier, not a standalone routing mode.

**Comment by aesculus** [comment]
This is the same as #499

**Comment by aesculus** [comment]
Closed the wrong one.

**Comment by aesculus** [comment]
I am repurposing the issue back to what I think is the original focus, to add in the other optimization models. The routing will be taken up in issue

**Comment by aesculus** [comment]
There begs a question if Minimize Energy should throttle the speed back to say 55 mph?  Right now it just looks for the route that will consume the least amount of energy, but it does not force a max speed that would be more efficient.  Without the speed adjust the results are probably not going to be significant.  At the same time I guess a user should be smart enough to know if they drive slower they will use less energy. 

So maybe it's up to the user to combine both the max speed and the minimize energy option, or do we do it for them and not tell them how we did it?

Of course the same could be said of minimizing stops too, but that is actually a different algorithm I have not written yet.

**Comment by EVGrokker** [comment]
My first thought is that Minimize Energy would mean 'take the route that has the least starting and stopping, or the least elevation change' (are the other obvious penalty factors?) 

A particular route does not imply a voluntary speed reduction, that should be an additional element introduced by the driver. Besides, there's no way for the app to tell them 'you should be driving 45 in this 55 section, then speed up to 60 in this 70 zone'. They can inform the app that they intend to drive like that using the PF slider, but it doesn't go the other way, other than the implicit speeds associated with the recommended route.

Of course, a route may be less-power consuming by virtue of its speed limits, like a local road paralleling a major highway. But that probably has more stop and go.

**Comment by aesculus** [comment]
I agree we should not change the speed.  I think I see a hypermiling tutorial coming on.

>My first thought is that Minimize Energy would mean 'take the route that has the least starting and stopping, or the least elevation change' (are the other obvious penalty factors?)

The optimization algorithms are not that sophisticated. Basically it uses all the info available on how much energy each route segment takes. It checks to make sure you can get between segments with the energy you have available. If you cannot make those segments with the battery capacity and nominal consumption, it discards those as impossible. It captures the energy required for the kept segments.
Then it computes the times (drive and charge), and distances.

Now for the optimization:  Depending on which model you choose it optimizes by either minimizing time (charge + drive), energy, or distance.  It does not change the underlying algorithm of seeking out paths that are better for elevation or drive slower etc.  If a path uses less energy, for whatever reason, that will show up as less charging time and less energy. Only the distance one would not be affected in that case.

Optimizing for least stops is a separate algorithm that I have not written yet.  Basically it would charge as much as it could so you could skip as many chargers as possible. Times would go out the window because charging that last 10% is a killer in time. It's one of those "if I build it they will never use it" scenarios so I am not rushing into that one.

**Comment by aesculus** [comment]
In V1.2 (76) I am taking a first pass at all but minimize stops. Here is an example of a trip from Sacramento (S90D) to San Diego using all three (image order): minimize time, minimize energy, minimize distance. The effects are very subtle in this particular scenario. Changing your driving speed and the weather probably has much more impact.

![image](https://user-images.githubusercontent.com/283364/29237952-e9938d0a-7edd-11e7-9db1-8241ff26b9cb.png)

**Comment by EVGrokker** [comment]
As you say, the effects are subtle, but real.

As more charging stations come online, these options will become more meaningful. 

Explanations in Help and Tutorials will need to point out that the optimization models are constrained, but will become more effective in time.

It's interesting to compare the Phi factor in the three models - it tracks correctly. Minimize time has the best Phi at 88, Minimize energy has the worst Phi at 85, and Minimize distance is in the middle at 86. Those numbers make sense.
