### ISSUE TITLE
Review Edit Segments Panel on MST

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#90]
Right now when no charger is involved the app will figure out how much charge is left over from the prior segment and make it the departure SOC for the next segment. However the user can override this today.

If there is a charger involved it defaults to the origin SOC then that should be OK.

Should there be a way to only edit the Origin SOC % for other than the original origin from the waypoint Edit panel and then always disable the segment Origin SOC %?

**Comment by EVGrokker** [comment]
I think it's important to do the calculation with the user's pre-defined Default Origin SoC from Settings, but to allow an individual segment's Origin SoC to be edited for all segments. Consider this scenarios:

Scenario 1)
My Day 1 Destination is a Hotel with an HPWC destination charger, and they claim that they will reserve it for me as part of my stay. So, I fully expect that upon my Day 2 departure, I'll be at my default 80% SoC.  

However, upon checking into the hotel, I'm informed that the HPWC is out of commission, or otherwise engaged. They happily offer me the use of a 110v outlet. Grumble grumble.

So the next morning I check my SoC and adjust the actual charge level to match the sad reality. I refresh the segment to learn whether or not I can stick to my original charging plan, or if I need to adjust to find a booster charge.

Scenarion 2)
Consider my Day 1 departure from Home, where I always charge to my default SoC. For some unanticipated reason (power failure, forgot to plug in the night before, ran a few errands in the morning before actually departing) I'm not starting with my default SoC. There should be a way to edit the first segment's SoC and refresh the segment to get EVTO's opinion of my charging itinerary for the day.

**Comment by aesculus** [comment]
I have changed the Edit Segment Details panel to allow the origin SOC to be changed on any Pro trip. The Destination Reserve will be disabled if the trip is the last one.
