### ISSUE TITLE
SoC not properly displayed at beginning of 2nd segment in O&B trip

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#93]
Reference trip ID [5bbafwn92acf41d2txxvxn], PIN 1234.

View segment 1 Destination, 'Tesla Supercharger'. It shows an arrival SoC of 63%.

View segment 2 Origin (also 'Tesla Supercharger'). It shows 'Charge to' of 63%. That's a bug.

View segment 2 SoC tab. It shows charging to ~72% at the Tesla Supercharger stop. That's correct.

View Trip Summary. Origin item shows 'Charge to 63% before departing'. That's a bug.

View Costco Wholesale (second item, first stop). That shows arrival SoC of 70%. That's correct.

**Comment by aesculus** [comment]
>View segment 1 Destination, 'Tesla Supercharger'. It shows an arrival SoC of 63%.

There is something weird about this trip. Seems that there are extra stops at the destination. The Burlington charger is added automatically and also when optimizing.

Did you add the Burlington charger manually?

Also when I delete the manual charger and reoptimize. It goes yellow at 70% because the destination was set at Min Arrival SOC at 70%. Why?

There was also an extra waypoint at Costco.  You don't need two 100 yards from each other.

Anyway I cleaned this up, optimized it and returned it for you to look at.
